[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.135.3",
    "httpx>=0.28.1",
    "pydantic-settings>=2.13.1",
    "python-jose>=3.5.0",
    "supabase>=2.28.3",
    "tencentcloud-sdk-python>=3.1.69",
    "uvicorn[standard]>=0.42.0",
]

[tool.pyright]
include = ["."]
exclude = ["**/__pycache__"]
pythonVersion = "3.13"
venvPath = "."
venv = ".venv"
typeCheckingMode = "basic"