[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.135.2",
    "python-dotenv>=1.2.2",
    "tencentcloud-sdk-python-asr>=3.1.51",
    "tencentcloud-sdk-python-common>=3.1.63",
    "tencentcloud-sdk-python-ocr>=3.1.62",
    "uvicorn[standard]>=0.42.0",
    "zhipuai>=2.1.5.20250825",
]
